spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: false

logging:
  level:
    com.healthcare: INFO
    org.springframework.web: WARN
